// Documentation generator -- 2026-07-12 10:58:45
import { FileAnalysis } from '../utils/ast';

export interface GeneratedDoc {
  filePath: string;
  markdown: string;
  generatedAt: string;
  functionCount: number;
  linesOfCode: number;
}

export function generateMarkdown(analysis: FileAnalysis): GeneratedDoc {
  const lines: string[] = [];
  const filename = analysis.filePath.split('/').pop() ?? analysis.filePath;

  lines.push('# ' + filename);
  lines.push('');
  lines.push('> Auto-generated by CodeLore | ' + new Date().toISOString());
  lines.push('');
  lines.push('## Overview');
  lines.push('');
  lines.push('| Property | Value |');
  lines.push('|---|---|');
  lines.push('| Lines of Code | ' + analysis.linesOfCode + ' |');
  lines.push('| Functions | ' + analysis.functions.length + ' |');
  lines.push('| Imports | ' + analysis.imports.length + ' |');
  lines.push('| Complexity | ' + analysis.complexity + ' |');
  lines.push('');

  if (analysis.imports.length > 0) {
    lines.push('## Dependencies');
    lines.push('');
    analysis.imports.forEach(imp => lines.push('- ' + imp + ''));
    lines.push('');
  }

  if (analysis.functions.length > 0) {
    lines.push('## Functions');
    lines.push('');
    analysis.functions.forEach(fn => {
      lines.push('### ' + fn.name + '');
      lines.push('');
      lines.push('- **Exported:** ' + fn.isExported);
      lines.push('- **Lines:** ' + fn.startLine + ' - ' + fn.endLine);
      if (fn.docComment) lines.push('- **Doc:** ' + fn.docComment);
      lines.push('');
    });
  }

  return {
    filePath: analysis.filePath,
    markdown: lines.join('\\n'),
    generatedAt: new Date().toISOString(),
    functionCount: analysis.functions.length,
    linesOfCode: analysis.linesOfCode,
  };
}